#include <Arduino.h>
#include <defines.h>
#include <getWifi.h>
#include <pins.h>
#include <fileFunc.h>
#include <LED.h>
#include <light.h>
#include <NTPClient.h>
#include <button.h>
#include <sendData.h>